stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - models/model.pkl
